# ==========================================
# ОСНОВНЫЕ НАСТРОЙКИ
# ==========================================
spring.application.name=ci-cd-maven-project
server.port=8080

# ==========================================
# THYMELEAF
# ==========================================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# ==========================================
# ЛОГИРОВАНИЕ
# ==========================================
logging.level.root=INFO
logging.level.org.example=DEBUG